name: Pull Requests

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          # - 8.x
          # - 10.x
          - 12.x

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, test and build
      run: |
        echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        npm install
        npm run lint
        npm test
        npm run test:passthrough
        npm run build
      env:
        TEST_ACCESS_TOKEN: ${{ secrets.TEST_ACCESS_TOKEN }}
        TEST_APPLICATION_ID: ${{ secrets.TEST_APPLICATION_ID }}
        TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}
        TEST_CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}
        TEST_REFRESH_TOKEN: ${{ secrets.TEST_REFRESH_TOKEN }}
        TEST_SCOPE: ${{ secrets.TEST_SCOPE }}
        CI: true
    - name: Commit files
      run: |
        git config --local user.email "scale-bot@scaleleap.com"
        git config --local user.name "Scale Bot"
        git add test/__recordings__
        git commit -m "test: add Polly recordings"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: 'polly-recordings'
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
